name: dartdirect
version: 1.6.0
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: Tools and packages for implementing a backend accessible from ExtJs Direct.
homepage: https://github.com/fromlabs/dartdirect
environment:
  sdk: ">=1.12.0 <2.0.0"
dependencies:
  logging: ^0.11.0
  mime: ^0.9.3
  dartregistry:
    version: ^1.2.5
    hosted:
      name: dartregistry
      url: http://pub.primeapp.it:9091
dependency_overrides:
  dartregistry:
    path: ../dartregistry