name: dartdirect
version: 1.1.3
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: Tools and packages for implementing a backend accessible from ExtJs Direct.
homepage: https://github.com/fromlabs/dartdirect
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dartregistry:
    git:
      ref: 1.1.1
      url: https://github.com/fromlabs/dartregistry
  intl: any
  logging: any
  mime: any
