name: dartdirect
author: Roberto Tassi <roberto.tassi@fromlabs.org>
version: 0.1.0
homepage: https://github.com/fromlabs/dartdirect
description: Tools and packages for implementing a backend accessible from ExtJs Direct.
dependencies:
  intl: any
  mime: any
