name: dartdirect
version: 1.2.0
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: Tools and packages for implementing a backend accessible from ExtJs Direct.
homepage: https://github.com/fromlabs/dartdirect
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dartregistry:
    git:
      ref: 1.2.1
      url: http://github.com/fromlabs/dartregistry
  intl: '>=0.12.4 <0.13.0'
  logging: '>=0.11.0 <0.12.0'
  mime: '>=0.9.3 <0.10.0'
