name: dartdirect
version: 1.8.1
author: Roberto Tassi <roberto.tassi@fromlabs.org>
description: Tools and packages for implementing a backend accessible from ExtJs Direct.
homepage: https://github.com/fromlabs/dartdirect
publish_to: http://pub.primeapp.it:9091
environment:
  sdk: ">=1.13.0 <2.0.0"
dependencies:
  logging: ^0.11.0
  stack_trace: ^1.6.0
  mime: ^0.9.3
  dartregistry: ^1.3.0